### ISSUE TITLE
Barrel distortion shader needs to be fixed, as it is now it is plain wrong

### ISSUE THREAD

**Issue by Fragilem17** [jonathanhart/oculus-ane#10]
some stuff i figured out:

The texture the fragment shader in ran on in away3d is not 640 by 800 but 1024x1024
The actual colored pixels are in the center of the 1024x1024 texture.

**Comment by Fragilem17** [comment]
Did a full rewrite and commented the hell out of the shader following the sdk code to the letter.
but even weirder unusable results..  To tired to continue now! 

To enable the shader, uncomment line 48 in OculusView.as
OculusBarrelDistortionTask is where the fragment code is written.

somebody else please! both my, by now pretty wrecked, eyes are on you guys :-) I gave it my best 2 shots.
don't know if i have the mental strength to stare another full night at AGAL code.

**Comment by jonathanhart** [comment]
I'll take a look at some stuff later today. I FINALLY have a holiday!! AGAL
is no walk in the park but I have done a few shaders so I do know the
language fairly well :)

**Comment by Fragilem17** [comment]
Great Jonathan!
Don't forget to relax a bit too though :-)

Should you or anyone else have a look at it, some more info:
- OculusBarrelDistortionTask, like it is now, does not take a left or right eye into account yet.
- The problem probably starts from the beginning as the texture's (0,0) is not where the first colored pixel is
  (the real texture is 1024x1024 instead of 640x800)
- Still not entirely sure where on the 1024 texture the 640 is located (think centered)
- The shader runs independently for each eye in each view, so there are 2 texture maps, just saying because in the SDK they have only one big texture containing both camera views. We don't.
- I've been using page 28 through 30 of the Oculus_SDK_Overview.pdf as my guide

Best of luck.

**Comment by jonathanhart** [comment]
Nice! Would you guys consider upgrading to the latest AIR 3.8 beta, which
supports Rectangle textures? It might alleviate this issue and reduce the
complexity..

**Comment by Fragilem17** [comment]
Sure no problem!

**Comment by Fragilem17** [comment]
Just upgraded to air 3.8 beta and the texture is still 1024.. I think it's something in the way away sets up it's filters.

**Comment by Fragilem17** [comment]
Just committed the demo with all shader constants as parameters that can be easily edited using simpleGUI sliders.

**Comment by Fragilem17** [comment]
WOOOOT!! that looks more like it! commited
