### ISSUE TITLE
Using ANE with FlashDevelop

### ISSUE THREAD

**Issue by malDuffin** [jonathanhart/oculus-ane#14]
Hi there,

Do you have any hints with regarding getting the ANE working with FlashDevelop?

I've tried a few things to no avail, and have posted here just in case someone else has already done it...

http://www.flashdevelop.org/community/viewtopic.php?f=13&t=10893&p=48906#p48906

**Comment by robertflesch** [comment]
How tied to Away3D is the oculus-ANE? 
I have my own 3d engine that I would like to try this with.
I followed the discussion on the flashdevelop forums.

**Comment by Fragilem17** [comment]
The ANE in itself is not tied to Away3D in any sense, the ANE only exposes the rotational tracking sensor and the HMD properties. (the data you need to correctly render stuff in your own engine)

That being said, the shader to do the warping is build on top of the filter system of away but is easily strapped out to use as a base for your own. If you could improve on it, that would also be greatly appreciated.

**Comment by robertflesch** [comment]
Thanks Fragilem17

Great news!

Shaders are not my area of expertise. I can tweak them, and write simple ones. But if the ANE shader is something I can add to do post processing that would be excellent. I will take a look at it today.

**Comment by jonathanhart** [comment]
I am closing this because the engine specific implementations should only be devoted to publicly available engines. Private engines don't really have any code that can be committed for them.

**Comment by jonathanhart** [comment]
Also, the ANE should work with FlashDevelop provided the latest checkins on the PC side..
