### ISSUE TITLE
Rebuild with latest SDK for DK2 support

### ISSUE THREAD

**Issue by malDuffin** [jonathanhart/oculus-ane#19]
Would it be possible to get a rebuild with the latest SDK, to support the newly released DK2 and open up access to the new positional tracking API?

**Comment by Fragilem17** [comment]
I think it would be possible :-) but time is in short supply at the moment. Hope to get some free time in the next weeks.

**Comment by malDuffin** [comment]
Cheers! Am about to add OR support to a current project, so looking to try out the latest versions of everything :)

**Comment by mrmmaclean** [comment]
The beauty of working with Adobe Native Extensions is that virtually ANY
function in a C/C++ library or SDK can be accessed if you follow these 3
basic steps:
1. Find the function you want to expose and add it to the object's list of
   functions
2. Create an AS3 equivalent of the function
3. Convert the data types appropriately so Flash doesn't just get a bunch
   of garbage.

All basic tutorials on creating ANEs I've found show these steps, and if
you can already do any amount of programming, it would only take a few
minutes to add what you need to your own project. The foundation is already
there in the Rift ANE source, simply add a couple more lines and ask Jon or
Tom to push it for you.

I might get back to this awesome project in the future (considering I
helped start it) but for the time being I feel like I would be doing
volunteer work for Facebook, and I have absolutely no interest in giving
them any of my time (which is probably about as much interest as that
company actually has in the Rift technology to begin with, beyond owning
yet another piece of our lives that is).

-Mike

**Comment by jonathanhart** [comment]
Please email me at jonathan.hart@gmail.com and I can provide a version of the Ane calibrated to the Dk 2.. I don't have one to test w but this version worked w the dk2 prototype and was tested by Oculus to work

**Comment by Fragilem17** [comment]
I'd be happy tot test it Jonathan. You have my email i think.

**Comment by jonathanhart** [comment]
I have upgraded the SDK to 0.4.1 which should now allow support for DK2. Let me know if you have issues. PC version is on its way.
