### ISSUE TITLE
Windows ANE Crashes Adobe AIR

### ISSUE THREAD

**Issue by BigPhilCombo** [jonathanhart/oculus-ane#5]
When I run the demo projects the ANE crashes AIR. (I now have my Oculus Rift)  I would be happy to debug the C++ portion but am not sure how to do that.  If someone could direct me to some documentation on how to debug ANE's then I can probably take a look at it this week .

**Comment by jonathanhart** [comment]
Hi there, I wish I had better ways of debugging the native side of ANEs at runtime. It was a major headache on the osx side of things as I could not find a way to efficiently debug that side short of piping stderr to a log and instrumenting the hell out of everything. I also don't have Windows so I can't help out at this time..

**Comment by BigPhilCombo** [comment]
Ok well I will try out with just logging parts and will figure it out from
there.

On Mon, Jun 24, 2013 at 5:07 PM, Jonathan Hart notifications@github.comwrote:

> Hi there, I wish I had better ways of debugging the native side of ANEs at
> runtime. It was a major headache on the osx side of things as I could not
> find a way to efficiently debug that side short of piping stderr to a log
> and instrumenting the hell out of everything. I also don't have Windows so
> I can't help out at this time..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonathanhart/oculus-ane/issues/5#issuecomment-19935897
> .

## 

Phillip Chertok

**Comment by Fragilem17** [comment]
You sure the oculus ane is crashing it? On win8 the ane for the joystick
was crashing air... When i disable that one it runs fine (doing a release
build with the joystick ane and then running in compatibility mode works
fine)

**Comment by BigPhilCombo** [comment]
It worked fine when I disabled the Oculus ANE but I will double check to
make sure that was the culprit.

On Mon, Jun 24, 2013 at 5:10 PM, Tom Goethals notifications@github.comwrote:

> You sure the oculus ane is crashing it? On win8 the ane for the joystick
> was crashing air... When i disable that one it runs fine (doing a release
> build with the joystick ane and then running in compatibility mode works
> fine)
> 
> On Monday, June 24, 2013, pchertok wrote:
> 
> > When I run the demo projects the ANE crashes AIR. (I now have my Oculus
> > Rift) I would be happy to debug the C++ portion but am not sure how to
> > do
> > that. If someone could direct me to some documentation on how to debug
> > ANE's then I can proboably take a look at it this week .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jonathanhart/oculus-ane/issues/5>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonathanhart/oculus-ane/issues/5#issuecomment-19936109
> .

## 

Phillip Chertok

**Comment by mrmmaclean** [comment]
It might be the ANE if you don't have it plugged in since there's no compatibility support beyond you manually checking if it's plugged in (using isSupported).

Either way, here's what I used to learn how to debug the DLL: http://rhuno.com/flashblog/2013/04/07/tutorial-debugging-native-extensions/

**Comment by BigPhilCombo** [comment]
Ahh terrific, thanks!

On Mon, Jun 24, 2013 at 7:23 PM, mrmmaclean notifications@github.comwrote:

> It might be the ANE if you don't have it plugged in since there's no
> compatibility support beyond you manually checking if it's plugged in
> (using isSupported).
> 
> Either way, here's what I used to learn how to debug the DLL:
> http://rhuno.com/flashblog/2013/04/07/tutorial-debugging-native-extensions/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonathanhart/oculus-ane/issues/5#issuecomment-19943141
> .

## 

Phillip Chertok

**Comment by mrmmaclean** [comment]
I know it seems silly but also make sure you have the most recent version of the AIR runtime. The demos run fine for me and moving the Rift around makes the scenes (and my own little debugger project) react accordingly without crashes.

**Comment by mrmmaclean** [comment]
I'll be back to things soon enough but real life has been keeping me busy. Work and the fact that half my city is under water at the moment is a bummer!

**Comment by BigPhilCombo** [comment]
Ok well it does actually seem to be working now.  I was certain that the
Rift was connected as I had just run the supplied demos.  ADL does crash
when I exit though but it's not an issue until a release.   Thanks!

On Mon, Jun 24, 2013 at 7:31 PM, mrmmaclean notifications@github.comwrote:

> I'll be back to things soon enough but real life has been keeping me busy.
> Work and the fact that half my city is under water at the moment is a
> bummer!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonathanhart/oculus-ane/issues/5#issuecomment-19943475
> .

## 

Phillip Chertok

**Comment by mrmmaclean** [comment]
In your Flex app add a "close" function which calls dispose() on the ANE.

**Comment by mrmmaclean** [comment]
It is explained near the end of this tutorial video: http://www.screencast.com/t/rnF5F0h9t1
(though that should be in the demo project itself haha)

**Comment by BigPhilCombo** [comment]
OculusANE does not have a dispose() method.

On Mon, Jun 24, 2013 at 7:49 PM, mrmmaclean notifications@github.comwrote:

> It is explained near the end of this tutorial video:
> http://www.screencast.com/t/rnF5F0h9t1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jonathanhart/oculus-ane/issues/5#issuecomment-19944258
> .

## 

Phillip Chertok

**Comment by mrmmaclean** [comment]
Yeah, derp, I just realized that... Feel free to add one! I actually had all that incorporated in my original version but I wanted everything to "just work" with what was already in the greater project scope so I removed a lot of my own functionality. Will work on that when I get the chance!

**Comment by mrmmaclean** [comment]
Alright, I added the method. Will be updated when jonathanhart commits it.

**Comment by jonathanhart** [comment]
I have done one better and added you guys as collaborators on the project. Hopefully this means you can commit directly into the repo. Let me know if there are problems!

**Comment by mrmmaclean** [comment]
Done! Thanks!

**Comment by Fragilem17** [comment]
Implemented the dispose method in the new away3d demo working like a charm. closing this issue
