### ISSUE TITLE
Away3d and other implementations

### ISSUE THREAD

**Issue by Fragilem17** [jonathanhart/oculus-ane#7]
Hi Guys,

We have the frameworks folder now with a stereo implementation.
(com\numeda\oculus\away3d)

And in the away demo i've got a half finished thing with another approach as the one in the frameworks folder. 
(be\but\oculus)

I know (from twitter) Jonathan, you where going to try with the multicam/multiview approach like in the demo to.

Should i make a new classpath inside the frameworks folder (outside of the respective demo folders) and reference the code in the demo from there?

Should we maybe make the frameworks folder create a library swf that can be referenced directly? (during development this kind of sucks i think)

any other thoughts on how to continue this thing? It should be super easy and clear from first sight on how to contribute to this repository so other dev's from other engines can contribute.

Tom

**Comment by Fragilem17** [comment]
Best to ignore this thread until we have the folder structure figured out in the other one... sorry (to fast and eager)

**Comment by jonathanhart** [comment]
Yes, I was going to just use your code!

It might be best to move the folder structure to something simple and
generic, such as "oculusane"
