### ISSUE TITLE
Windows ANE getHMDInfo(); returns an object with empty properties

### ISSUE THREAD

**Issue by Fragilem17** [jonathanhart/oculus-ane#8]
It returns an object with all the properties that should be there.
 (HScreenSize, eyeToScreenDistance and so on) 
but all the values are set to 0.

No idea how to solve it myself but a test is available in the away3d demo. (OculusScene3D.as line 43, needs some uncommenting)

Who do i assign this one to?

**Comment by mrmmaclean** [comment]
If I'm not mistaken, you have to have the value names match those given when the objects are created in the C side of things, ie. "HScreenSize" rather than "hScreenSize".

**Comment by Fragilem17** [comment]
Not really getting what you mean. Are you saying the error is not on the c
side but in AS maybe?

In AS i am holding the debugger at a breakpoint just after
var someObj:Object = getHmdInfo();

someObj contains at that point a bunch of props, all starting with a
capital, but the values are 0.

that is why i created a dummy object with some hardcoded default values in
the demo. (those props are lowercase and that would need to be changed but
is not really the problem now)

If that is not what you meant, could you please elaborate a bit more on
what needs changing on the c side? Dont really know c :-)

**Comment by mrmmaclean** [comment]
Don't initialize the object with new Object(), but instead make infoObj public (or private with get/set) and initialize it with

infoObj = _oculusAne.getHMDInfo();

In OculusScene3D.as, you have it initialized with var infoObj:Object = new Object(); (line 41) and I think that might be breaking it.

**Comment by Fragilem17** [comment]
Tried what you said but that does not seem to fix the problem. Also tried getting hmdInfo at a later point in time (not just after the instantiation of OculusANE).

Also want to add to the issue, the values are almost all 0, (apart from the first index inside Vector DistortionK being 1) but the property ChromAbCorrection is also missing.

other ideas? somebody willing to take a look at the c side of things, or maybe testing on their systems?

**Comment by Fragilem17** [comment]
Ok guys fixed it in the c code, also added the chromatic aberration stuff. learning heaps on this thing!
